CREATE TABLE IF NOT EXISTS schema_migrations (version text PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE auth_challenges (id text PRIMARY KEY, address text NOT NULL, message text NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE INDEX auth_challenges_expiry ON auth_challenges (expires_at);
CREATE TABLE auth_refresh_tokens (id text PRIMARY KEY, address text NOT NULL, session_id text NOT NULL, expires_at timestamptz NOT NULL, used_at timestamptz);
CREATE INDEX auth_refresh_tokens_expiry ON auth_refresh_tokens (expires_at);
CREATE TABLE activity_subscriptions (owner text NOT NULL, watched_address text NOT NULL, active boolean NOT NULL, next_block numeric(78,0) NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, last_processed_block numeric(78,0), last_processed_block_hash text, PRIMARY KEY(owner, watched_address));
CREATE INDEX activity_subscriptions_active ON activity_subscriptions (active, updated_at);
CREATE TABLE activity_actions (owner text NOT NULL, watched_address text NOT NULL, public_id text NOT NULL, token text NOT NULL, token_decimals integer NOT NULL, token_symbol text, amount text NOT NULL, amount_units numeric(78,0) NOT NULL, classification text NOT NULL, classification_source text NOT NULL, counterparty text NOT NULL, transaction_hash text NOT NULL, block_hash text NOT NULL, block_number numeric(78,0) NOT NULL, log_index numeric(78,0) NOT NULL, occurred_at timestamptz NOT NULL, confirmations numeric(78,0) NOT NULL, PRIMARY KEY(owner, watched_address, public_id));
CREATE INDEX activity_actions_owner_time ON activity_actions (owner, occurred_at DESC, public_id DESC);
CREATE TABLE activity_worker_leases (name text PRIMARY KEY, holder text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE trading_orders (id text PRIMARY KEY, chain_id text NOT NULL, maker text NOT NULL, router text NOT NULL, order_hash text NOT NULL, encoded_order text NOT NULL, base_token text NOT NULL, quote_token text NOT NULL, side text NOT NULL, price text NOT NULL, original_base_amount text NOT NULL, remaining_base_amount text NOT NULL, original_base_units numeric(78,0) NOT NULL, remaining_base_units numeric(78,0) NOT NULL, base_decimals integer NOT NULL, quote_decimals integer NOT NULL, status text NOT NULL, block_number numeric(78,0) NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL, UNIQUE(order_hash, router));
CREATE INDEX trading_orders_pair ON trading_orders (base_token, quote_token, status);
CREATE INDEX trading_orders_maker_time ON trading_orders (maker, updated_at DESC, id DESC);
CREATE TABLE trading_fills (id text PRIMARY KEY, order_id text NOT NULL, transaction_hash text NOT NULL, maker text NOT NULL, taker text NOT NULL, base_token text NOT NULL, quote_token text NOT NULL, base_amount text NOT NULL, quote_amount text NOT NULL, price text NOT NULL, block_number numeric(78,0) NOT NULL, occurred_at timestamptz NOT NULL);
CREATE INDEX trading_fills_maker_time ON trading_fills (maker, occurred_at DESC, id DESC);
CREATE INDEX trading_fills_pair_time ON trading_fills (base_token, quote_token, occurred_at DESC, id DESC);
CREATE TABLE trading_intents (id text PRIMARY KEY, maker text NOT NULL, command_hash text NOT NULL, command jsonb NOT NULL, status text NOT NULL, nonce text NOT NULL, valid_before timestamptz NOT NULL, signature text);
CREATE INDEX trading_intents_active ON trading_intents (status, valid_before, id);
CREATE TABLE trading_protocol_logs (id text PRIMARY KEY, address text NOT NULL, block_number numeric(78,0) NOT NULL, block_hash text NOT NULL, transaction_hash text NOT NULL, log_index numeric(78,0) NOT NULL, topic0 text NOT NULL, topics jsonb NOT NULL, data text NOT NULL);
CREATE TABLE trading_checkpoints (name text PRIMARY KEY, block_number numeric(78,0) NOT NULL, block_hash text NOT NULL);
CREATE TABLE keeper_jobs (id text PRIMARY KEY, target text NOT NULL, data text NOT NULL, value numeric(78,0) NOT NULL, state text NOT NULL, attempts integer NOT NULL, nonce numeric(78,0), transaction_hash text, submitted_at timestamptz, max_fee_per_gas numeric(78,0), lease_owner text, lease_until timestamptz, completed_block numeric(78,0), failure_reason text);
CREATE INDEX keeper_jobs_claim ON keeper_jobs (state, lease_until, id);
CREATE TABLE trigger_observations (id text PRIMARY KEY, proof_hash text NOT NULL, first_block numeric(78,0) NOT NULL, first_timestamp numeric(78,0) NOT NULL);
