import { addressSchema, positiveAmountSchema } from "@aqua/core";
import type { AuthenticatedPrincipal, RuntimeManifest } from "@aqua/core";
import { exactPermit2UpfrontRequirement, unpaidMcpResult } from "@aqua/x402-adapter";
import { z } from "zod";

const requestSchema=z.object({jsonrpc:z.literal("2.0"),id:z.union([z.string(),z.number()]),method:z.string(),params:z.unknown().optional()}).strict();
const callSchema=z.object({name:z.enum(["prepare_order","submit_order","prepare_amendment","submit_amendment","prepare_cancellation","submit_cancellation","get_order","prepare_withdrawal"]),arguments:z.record(z.string(),z.unknown()).default({}),_meta:z.record(z.string(),z.unknown()).optional()}).strict();
const prepareSchema=z.object({operationId:z.uuid(),sellToken:addressSchema,vault:addressSchema,atomicAmount:positiveAmountSchema}).strict();
const tools=["prepare_order","submit_order","prepare_amendment","submit_amendment","prepare_cancellation","submit_cancellation","get_order","prepare_withdrawal"].map((name)=>({name,description:`Ledger-policy constrained ${name.replaceAll("_"," ")}`,inputSchema:{type:"object",additionalProperties:false}}));
const hardware=(principal:AuthenticatedPrincipal):void=>{if(principal.authenticationMethods?.has("fido2")!==true||!principal.authenticationMethods.has("hwk"))throw new Error("MCP access token requires amr=fido2 hwk");};
export const handleMcp=async(request:Request,manifest:RuntimeManifest,authenticate:(token:string)=>Promise<AuthenticatedPrincipal>):Promise<Response>=>{const header=request.headers.get("authorization");if(header?.startsWith("Bearer ")!==true)return Response.json({jsonrpc:"2.0",id:null,error:{code:-32001,message:"Ledger FIDO2 bearer token required"}},{status:401,headers:{"www-authenticate":`Bearer resource_metadata="${manifest.auth.issuer}/.well-known/oauth-protected-resource"`}});try{const principal=await authenticate(header.slice(7));hardware(principal);const envelope=requestSchema.parse(await request.json());if(envelope.method==="initialize")return Response.json({jsonrpc:"2.0",id:envelope.id,result:{protocolVersion:"2025-06-18",capabilities:{tools:{}},serverInfo:{name:"aqua-ledger-mcp",version:"0.1.0"}}});if(envelope.method==="tools/list")return Response.json({jsonrpc:"2.0",id:envelope.id,result:{tools}});if(envelope.method!=="tools/call")return Response.json({jsonrpc:"2.0",id:envelope.id,error:{code:-32601,message:"Method not found"}});const call=callSchema.parse(envelope.params);if(call.name==="prepare_order"){const operation=prepareSchema.parse(call.arguments);const payment=exactPermit2UpfrontRequirement(manifest,operation);return Response.json({jsonrpc:"2.0",id:envelope.id,result:{...unpaidMcpResult(payment),content:[{type:"text",text:JSON.stringify({state:"payment-required",owner:principal.address,operationId:operation.operationId,vault:operation.vault})}]}});}return Response.json({jsonrpc:"2.0",id:envelope.id,result:{isError:true,content:[{type:"text",text:"Operation has not reached its required prepared or settled state"}]}});}catch(error:unknown){return Response.json({jsonrpc:"2.0",id:null,error:{code:-32602,message:error instanceof Error?error.message:"Invalid MCP request"}},{status:400});}};
