import { randomUUID } from "node:crypto";
import { rm } from "node:fs/promises";
import { PostgresKeeperJobRepository, PostgresTradingRepository, PostgresTradeTriggerRepository, createDatabase, closeDatabase } from "@aqua/adapters";
import { hexSchema, loadRuntimeManifest, localProfileDefaults, runtimeManifestHash } from "@aqua/core";
import { createPooledRpcClient, initializeCubane } from "@aqua/evm";
import type { Eip1559Transaction } from "@aqua/evm";
import { Keeper, OrderBookIndexer, TriggerEvaluator } from "@aqua/orderbook";
import { createSecretBroker } from "@aqua/security";

const manifest=await loadRuntimeManifest(Bun.argv);const defaults=localProfileDefaults;
const readyIndex=Bun.argv.indexOf("--ready-out");const readyOut=readyIndex<0?null:Bun.argv[readyIndex+1]??null;
initializeCubane();const database=createDatabase(manifest.services.databaseUrl);await database.connect();
const repository=new PostgresTradingRepository(database);await repository.initialize();
const rpc=createPooledRpcClient(manifest.chain,defaults.rpcTimeoutMs);
const indexer=new OrderBookIndexer(repository,rpc,{chainId:manifest.chain.id,contracts:manifest.indexer.contracts,startBlock:BigInt(manifest.indexer.startBlock),limitRouters:[manifest.contracts.limitSwapRouter.address],pairs:manifest.fixtures.pairs,confirmations:BigInt(manifest.indexer.confirmations),blockChunkSize:BigInt(defaults.orderbookBlockChunkSize)});
const broker=createSecretBroker(manifest);const identity=await broker.identity();
const keeperRepository=new PostgresKeeperJobRepository(database);await keeperRepository.initialize();
const signer={address:identity.keeper,sign:(transaction:Eip1559Transaction)=>broker.signEip1559(transaction)};
const keeper=new Keeper(keeperRepository,rpc,signer,{chainId:manifest.chain.id,allowedTargets:manifest.keeper.allowedTargets,allowedSelectors:manifest.keeper.allowedSelectors.map((selector)=>hexSchema.parse(selector)),gasLimit:defaults.keeperGasLimitCeiling,maxFeePerGas:defaults.keeperMaxFeePerGasCeiling,replacementSeconds:defaults.keeperReplacementSeconds,leaseSeconds:defaults.keeperLeaseSeconds});
const triggers=new TriggerEvaluator(repository,keeperRepository,{controller:manifest.contracts.intentController.address,matcher:manifest.contracts.boundedMatcher.address,factory:manifest.contracts.orderVaultFactory.address,minimumBlocks:BigInt(defaults.triggerMinimumBlocks),minimumSeconds:BigInt(defaults.triggerMinimumSeconds)},new PostgresTradeTriggerRepository(database));
console.log(JSON.stringify({level:"info",component:"order-worker",manifestHash:runtimeManifestHash(manifest)}));
const workerId=randomUUID();const runCycle=async():Promise<void>=>{await indexer.runOnce();const head=await rpc.blockNumber();if(head>=BigInt(manifest.indexer.confirmations)){const confirmed=await rpc.block(head-BigInt(manifest.indexer.confirmations));await triggers.runOnce(confirmed.number,confirmed.timestamp);}await keeper.runOnce(workerId);};
let stopped=false;let timer:ReturnType<typeof setTimeout>|undefined;const schedule=():void=>{if(stopped)return;timer=setTimeout(()=>{void runCycle().catch((error:unknown)=>{console.error(JSON.stringify({level:"error",component:"order-worker",message:error instanceof Error?error.message:"Unknown worker error"}));}).finally(schedule);},defaults.orderbookPollIntervalSeconds*1_000);};
await runCycle();if(readyOut!==null)await Bun.write(readyOut,"ready\n");schedule();const shutdown=async():Promise<void>=>{stopped=true;if(timer!==undefined)clearTimeout(timer);if(readyOut!==null)await rm(readyOut,{force:true});await closeDatabase(database);};process.once("SIGTERM",()=>{void shutdown();});process.once("SIGINT",()=>{void shutdown();});
