import type { SQL } from "bun";
import type { ActivityClassification, Address, Hash } from "@aqua/core";
import type { ActionFilter, ActionPage, ActivityRepository, ActivitySubscription, TokenAction } from "@aqua/activity";
interface SubscriptionRow {owner:Address;watched_address:Address;active:boolean;next_block:string;created_at:Date;updated_at:Date;last_processed_block:string|null;last_processed_block_hash:Hash|null}
interface ActionRow {public_id:string;owner:Address;watched_address:Address;token:Address;token_decimals:number;token_symbol:string|null;amount:string;amount_units:string;classification:ActivityClassification;classification_source:"transferSemantics"|"inferredCounterflow";counterparty:Address;transaction_hash:Hash;block_hash:Hash;block_number:string;log_index:string;occurred_at:Date;confirmations:string}
const subscription=(r:SubscriptionRow):ActivitySubscription=>({owner:r.owner,watchedAddress:r.watched_address,active:r.active,nextBlock:BigInt(r.next_block),createdAt:r.created_at,updatedAt:r.updated_at,...(r.last_processed_block===null?{}:{lastProcessedBlock:BigInt(r.last_processed_block)}),...(r.last_processed_block_hash===null?{}:{lastProcessedBlockHash:r.last_processed_block_hash})});
const action=(r:ActionRow):TokenAction=>({id:r.public_id,owner:r.owner,watchedAddress:r.watched_address,token:r.token,tokenDecimals:r.token_decimals,tokenSymbol:r.token_symbol,amount:r.amount,amountUnits:r.amount_units,classification:r.classification,classificationSource:r.classification_source,counterparty:r.counterparty,transactionHash:r.transaction_hash,blockHash:r.block_hash,blockNumber:BigInt(r.block_number),logIndex:BigInt(r.log_index),occurredAt:r.occurred_at,confirmations:BigInt(r.confirmations)});
export class PostgresActivityRepository implements ActivityRepository {
 private readonly db: SQL;
 public constructor(db:SQL) { this.db=db; }
 public async initialize():Promise<void>{await this.db`SELECT 1`;}
 public async subscribe(owner:Address,watchedAddress:Address,firstBlock:bigint,now:Date):Promise<{readonly subscription:ActivitySubscription;readonly created:boolean}>{const rows=await this.db<SubscriptionRow[]>`INSERT INTO activity_subscriptions(owner,watched_address,active,next_block,created_at,updated_at) VALUES(${owner},${watchedAddress},true,${firstBlock.toString()},${now},${now}) ON CONFLICT(owner,watched_address) DO UPDATE SET active=true,updated_at=EXCLUDED.updated_at RETURNING owner,watched_address,active,next_block::text,created_at,updated_at,last_processed_block::text,last_processed_block_hash`;const row=rows[0];if(row===undefined)throw new Error("Subscription upsert did not return a row");return {subscription:subscription(row),created:row.created_at.getTime()===now.getTime()};}
 public async unsubscribe(owner:Address,watchedAddress:Address,now:Date):Promise<boolean>{const r:readonly unknown[]=await this.db`UPDATE activity_subscriptions SET active=false,updated_at=${now} WHERE owner=${owner} AND watched_address=${watchedAddress} AND active=true RETURNING owner`;return r.length===1;}
 public async listSubscriptions(owner:Address):Promise<readonly ActivitySubscription[]>{return (await this.db<SubscriptionRow[]>`SELECT owner,watched_address,active,next_block::text,created_at,updated_at,last_processed_block::text,last_processed_block_hash FROM activity_subscriptions WHERE owner=${owner} ORDER BY created_at`).map(subscription);}
 public async listActiveSubscriptions(limit:number):Promise<readonly ActivitySubscription[]>{return (await this.db<SubscriptionRow[]>`SELECT owner,watched_address,active,next_block::text,created_at,updated_at,last_processed_block::text,last_processed_block_hash FROM activity_subscriptions WHERE active=true ORDER BY updated_at LIMIT ${limit}`).map(subscription);}
 public async storeBatch(s:ActivitySubscription,actions:readonly TokenAction[],next:bigint,hash:Hash,now:Date):Promise<void>{await this.db.begin(async tx=>{for(const a of actions)await tx`INSERT INTO activity_actions(owner,watched_address,public_id,token,token_decimals,token_symbol,amount,amount_units,classification,classification_source,counterparty,transaction_hash,block_hash,block_number,log_index,occurred_at,confirmations) VALUES(${a.owner},${a.watchedAddress},${a.id},${a.token},${a.tokenDecimals},${a.tokenSymbol},${a.amount},${a.amountUnits},${a.classification},${a.classificationSource},${a.counterparty},${a.transactionHash},${a.blockHash},${a.blockNumber.toString()},${a.logIndex.toString()},${a.occurredAt},${a.confirmations.toString()}) ON CONFLICT DO NOTHING`;
 const grouped=new Map<Hash,TokenAction[]>();for(const a of actions){const group=grouped.get(a.transactionHash)??[];group.push(a);grouped.set(a.transactionHash,group);}for(const [transactionHash,group] of grouped){const sells=group.filter(a=>a.classification==="sell");const buys=group.filter(a=>a.classification==="buy");if(sells.length!==1||buys.length!==1||group.length!==2)continue;const sell=sells[0];const buy=buys[0];if(sell===undefined||buy===undefined||sell.token===buy.token)continue;const id=`${s.owner}:${s.watchedAddress}:${transactionHash}`;await tx`INSERT INTO subscribed_trades(id,owner,watched_address,transaction_hash,sell_token,buy_token,sell_amount,buy_amount,block_number,occurred_at,updated_at,raw_activity_ids) VALUES(${id},${s.owner},${s.watchedAddress},${transactionHash},${sell.token},${buy.token},${sell.amountUnits},${buy.amountUnits},${sell.blockNumber.toString()},${sell.occurredAt},${now},${JSON.stringify([sell.id,buy.id])}) ON CONFLICT(owner,watched_address,transaction_hash) DO NOTHING`;}
 const updated:readonly unknown[]=await tx`UPDATE activity_subscriptions SET next_block=${next.toString()},last_processed_block=${(next-1n).toString()},last_processed_block_hash=${hash},updated_at=${now} WHERE owner=${s.owner} AND watched_address=${s.watchedAddress} AND active=true AND next_block=${s.nextBlock.toString()} RETURNING owner`;if(updated.length!==1)throw new Error("Subscription cursor changed");});}
 public async rewind(s:ActivitySubscription,next:bigint,now:Date):Promise<void>{await this.db.begin(async tx=>{await tx`DELETE FROM subscribed_trades WHERE owner=${s.owner} AND watched_address=${s.watchedAddress} AND block_number>=${next.toString()}`;await tx`DELETE FROM activity_actions WHERE owner=${s.owner} AND watched_address=${s.watchedAddress} AND block_number>=${next.toString()}`;await tx`UPDATE activity_subscriptions SET next_block=${next.toString()},last_processed_block=NULL,last_processed_block_hash=NULL,updated_at=${now} WHERE owner=${s.owner} AND watched_address=${s.watchedAddress}`;});}
 public async listActions(f:ActionFilter):Promise<ActionPage>{const rows=await this.db<ActionRow[]>`SELECT public_id,owner,watched_address,token,token_decimals,token_symbol,amount,amount_units::text,classification,classification_source,counterparty,transaction_hash,block_hash,block_number::text,log_index::text,occurred_at,confirmations::text FROM activity_actions WHERE owner=${f.owner} AND (${f.watchedAddress??null}::text IS NULL OR watched_address=${f.watchedAddress??null}) AND (${f.classification??null}::text IS NULL OR classification=${f.classification??null}) AND (${f.from??null}::timestamptz IS NULL OR occurred_at>=${f.from??null}) AND (${f.to??null}::timestamptz IS NULL OR occurred_at<${f.to??null}) ORDER BY occurred_at DESC,public_id DESC LIMIT ${f.limit+1}`;return {items:rows.slice(0,f.limit).map(action),hasMore:rows.length>f.limit};}
 public async wipe(owner:Address,watchedAddress?:Address):Promise<bigint>{const r:unknown=await this.db`DELETE FROM activity_actions WHERE owner=${owner} AND (${watchedAddress??null}::text IS NULL OR watched_address=${watchedAddress??null})`;if(typeof r!=="object"||r===null||!("count" in r)||(typeof r.count!=="number"&&typeof r.count!=="bigint"))throw new Error("Invalid deletion result");return BigInt(r.count);}
 public async acquireLease(name:string,holder:string,now:Date,until:Date):Promise<boolean>{const r=await this.db<{holder:string}[]>`INSERT INTO activity_worker_leases(name,holder,expires_at) VALUES(${name},${holder},${until}) ON CONFLICT(name) DO UPDATE SET holder=EXCLUDED.holder,expires_at=EXCLUDED.expires_at WHERE activity_worker_leases.expires_at<=${now} OR activity_worker_leases.holder=${holder} RETURNING holder`;return r[0]?.holder===holder;}
}
