import type { SQL } from "bun";
import { addressSchema, hashSchema, hexSchema } from "@aqua/core";
import type { Hash } from "@aqua/core";
import type { KeeperJob, KeeperJobRepository, TriggerObservation, TriggerRepository } from "@aqua/orderbook";
type JobRow={id:string;target:string;data:string;value:string;state:"ready"|"submitted";attempts:number;nonce:string|null;transaction_hash:string|null;submitted_at:Date|null;max_fee_per_gas:string|null};
const job=(r:JobRow):KeeperJob=>({id:r.id,target:addressSchema.parse(r.target),data:hexSchema.parse(r.data),value:BigInt(r.value),state:r.state,attempts:r.attempts,...(r.nonce===null?{}:{nonce:BigInt(r.nonce)}),...(r.transaction_hash===null?{}:{transactionHash:hashSchema.parse(r.transaction_hash)}),...(r.submitted_at===null?{}:{submittedAt:r.submitted_at}),...(r.max_fee_per_gas===null?{}:{maxFeePerGas:BigInt(r.max_fee_per_gas)})});
export class PostgresKeeperJobRepository implements KeeperJobRepository,TriggerRepository { private readonly db: SQL; public constructor(db:SQL){this.db=db;} public async initialize():Promise<void>{await this.db`SELECT 1`;}
 public async claim(worker:string,now:Date,until:Date):Promise<KeeperJob|null>{const r=await this.db.begin(async tx=>tx<JobRow[]>`WITH candidate AS (SELECT id FROM keeper_jobs WHERE state IN ('ready','submitted') AND (lease_until IS NULL OR lease_until<=${now}) ORDER BY id FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE keeper_jobs j SET lease_owner=${worker},lease_until=${until},attempts=j.attempts+1 FROM candidate WHERE j.id=candidate.id RETURNING j.id,j.target,j.data,j.value::text,j.state,j.attempts,j.nonce::text,j.transaction_hash,j.submitted_at,j.max_fee_per_gas::text`);const row=r[0];return row===undefined?null:job(row);}
 public async markSubmitted(id:string,w:string,h:Hash,n:bigint,f:bigint,d:Date):Promise<void>{await this.db`UPDATE keeper_jobs SET state='submitted',transaction_hash=${h},nonce=${n.toString()},max_fee_per_gas=${f.toString()},submitted_at=${d},lease_owner=NULL,lease_until=NULL WHERE id=${id} AND lease_owner=${w}`;}
 public async markComplete(id:string,w:string,b:bigint):Promise<void>{await this.db`UPDATE keeper_jobs SET state='complete',completed_block=${b.toString()},lease_owner=NULL,lease_until=NULL WHERE id=${id} AND lease_owner=${w}`;}
 public async markFailed(id:string,w:string,reason:string):Promise<void>{await this.db`UPDATE keeper_jobs SET state='failed',failure_reason=${reason.slice(0,500)},lease_owner=NULL,lease_until=NULL WHERE id=${id} AND lease_owner=${w}`;}
 public async observation(id:string):Promise<TriggerObservation|null>{const r=await this.db<{id:string;proof_hash:string;first_block:string;first_timestamp:string}[]>`SELECT id,proof_hash,first_block::text,first_timestamp::text FROM trigger_observations WHERE id=${id}`;const x=r[0];return x===undefined?null:{intentId:x.id,proofHash:hashSchema.parse(x.proof_hash),firstBlock:BigInt(x.first_block),firstTimestamp:BigInt(x.first_timestamp)};}
 public async saveObservation(x:TriggerObservation):Promise<void>{await this.db`INSERT INTO trigger_observations(id,proof_hash,first_block,first_timestamp) VALUES(${x.intentId},${x.proofHash},${x.firstBlock.toString()},${x.firstTimestamp.toString()}) ON CONFLICT(id) DO UPDATE SET proof_hash=EXCLUDED.proof_hash,first_block=EXCLUDED.first_block,first_timestamp=EXCLUDED.first_timestamp`;}
 public async deleteObservation(id:string):Promise<void>{await this.db`DELETE FROM trigger_observations WHERE id=${id}`;}
 public async enqueue(x:KeeperJob):Promise<void>{await this.db`INSERT INTO keeper_jobs(id,target,data,value,state,attempts) VALUES(${x.id},${x.target},${x.data},${x.value.toString()},'ready',0) ON CONFLICT(id) DO NOTHING`;}
}
