import { describe, expect, test } from "bun:test";
import { addressSchema, runtimeManifestSchema } from "@aqua/core";
import { PERMIT2_ADDRESS, X402_EXACT_PERMIT2_PROXY, assertStandardTokenFunding, exactPermit2UpfrontRequirement, paymentIdentifier, unpaidMcpResult } from "../src/index.ts";

const address=(digit:string)=>addressSchema.parse(`0x${digit.repeat(40)}`);
const hash=(digit:string)=>`0x${digit.repeat(64)}`;
const contract=(digit:string)=>({address:address(digit),runtimeCodeHash:hash(digit)});
const manifest=runtimeManifestSchema.parse({schemaVersion:1,profile:"local-anvil",runId:"7b4df39d-33e8-41d2-9206-c8786f290dab",createdAt:"2026-09-08T00:00:00.000Z",chain:{id:31337,rpcUrl:"http://127.0.0.1:8545",genesisHash:hash("c"),deploymentBlock:"12"},services:{databaseUrl:"postgresql://aqua@127.0.0.1:5432/aqua",apiUrl:"http://localhost:3000",facilitatorUrl:"http://127.0.0.1:4022",brokerSocket:"/tmp/aqua-test.sock"},auth:{issuer:"http://localhost:3000",resource:"http://localhost:3000",rpId:"localhost",origin:"http://localhost:3000",pasetoPublicKeys:["k4.public.0QPCsCVAycJZIZ13J36BogFriPmY0KXmGf99Jb_Qr3k"]},contracts:{aqua:contract("1"),aquaSwapRouter:contract("2"),limitSwapRouter:contract("3"),wrappedNativeToken:contract("4"),intentController:contract("5"),orderVaultFactory:contract("6"),boundedMatcher:contract("7"),permit2:{address:PERMIT2_ADDRESS,runtimeCodeHash:hash("8")},x402ExactPermit2Proxy:{address:X402_EXACT_PERMIT2_PROXY,runtimeCodeHash:hash("9")}},fixtures:{tokens:[{...contract("a"),symbol:"TEST",decimals:18},{...contract("b"),symbol:"QUOTE",decimals:6}],pairs:[{baseToken:address("a"),quoteToken:address("b")}]},indexer:{contracts:[address("1")],startBlock:"12",confirmations:1},keeper:{allowedTargets:[address("6")],allowedSelectors:["0x12345678"]},secrets:{agent:"broker://agent",facilitator:"broker://facilitator",keeper:"broker://keeper",paseto:"broker://paseto"}});

describe("truthful software x402 simulation",()=>{
  test("requires exact Permit2 upfront funding into the order vault",()=>{const operation={operationId:"5ab5f748-8580-4c80-b91b-6a611975c87e",sellToken:address("a"),vault:address("d"),atomicAmount:"1250000000000000000"};const required=exactPermit2UpfrontRequirement(manifest,operation);expect(required).toMatchObject({x402Version:2,accepts:[{scheme:"exact",network:"eip155:31337",asset:operation.sellToken,amount:operation.atomicAmount,payTo:operation.vault,extra:{assetTransferMethod:"permit2",paymentFlow:"upfront",permit2:PERMIT2_ADDRESS,proxy:X402_EXACT_PERMIT2_PROXY,paymentIdentifier:paymentIdentifier(operation.operationId)}}]});expect(unpaidMcpResult(required)).toMatchObject({isError:true,_meta:{"x402/payment":required}});});
  test("accepts only an exact stable balance delta",()=>{expect(()=> { assertStandardTokenFunding({codePresent:true,allowance:100n,balanceBefore:10n,balanceAfter:110n,expectedDelta:100n,stableBalance:true}); }).not.toThrow();expect(()=> { assertStandardTokenFunding({codePresent:true,allowance:100n,balanceBefore:10n,balanceAfter:109n,expectedDelta:100n,stableBalance:true}); }).toThrow("exact balance-delta");expect(()=> { assertStandardTokenFunding({codePresent:true,allowance:100n,balanceBefore:10n,balanceAfter:110n,expectedDelta:100n,stableBalance:false}); }).toThrow();});
  test("supports dynamically validated ERC-20 assets and deployment chains",()=>{const required=exactPermit2UpfrontRequirement(manifest,{operationId:"5ab5f748-8580-4c80-b91b-6a611975c87e",sellToken:address("c"),vault:address("d"),atomicAmount:"1"});expect(required.accepts[0]?.asset).toBe(address("c"));const mainnet=exactPermit2UpfrontRequirement({...manifest,chain:{...manifest.chain,id:1}},{operationId:"5ab5f748-8580-4c80-b91b-6a611975c87e",sellToken:address("a"),vault:address("d"),atomicAmount:"1"});expect(mainnet.accepts[0]?.network).toBe("eip155:1");});
});
